### ISSUE TITLE
markdown2html里主题想修改脚注title

### ISSUE THREAD

**Issue by Leslie-Lu** [shenweiyan/Markdown2Html#8]
![微信图片_20240904174031](https://github.com/user-attachments/assets/9e8c1109-84c9-4480-b5f3-06ecc86f653f)

比如，想把脚注title中的**参考资料**改成**参考文献**，目前似乎不能实现。

**Comment by shenweiyan** [comment]
在选中的主题样式中自定义 CSS，加入下面几行代码应该就可以了：
```css
/*自定义样式，实时生效*/
#nice .footnotes-sep:before {
  content: "参考文献";
  display: block;
}
```
![Clip_2024-09-05_09-12-08](https://github.com/user-attachments/assets/ef393a90-ce95-4005-9e5b-1b1e34251f6d)
